# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


genres = Genre.create([{name: "Fiction"}, {name: "Non-Fiction"}, {name: "History"}, {name: "Philosophy"}, {name: "Mystery"}])

Book.create(title: "Moby Dick", author: "Herman Melville", description: "One of the great works of American literature, Moby Dick is the epic tale of one man's fight against a force of nature. The outcast youth Ishmael, succumbing to wanderlust during a dreary New England autumn, signs up for passage aboard a whaling ship. The Pequod sails under the command of the one-legged Captain Ahab, who has set himself on a monomaniacal quest to capture the cunning white whale that robbed him of his leg: Moby-Dick. Capturing life on the sea with robust realism, Melville details the adventures of the colorful crew aboard the ship as Ahab pursues his crusade of revenge, heedless of all cost. This masterfully symbolic drama of the conflict between man and his fate has a special intensity that listeners will not soon forget.", genre: Genre.first)
Book.create(title: "1984", author: "George Orwell", description: "Among the seminal texts of the 20th century, Nineteen Eighty-Four is a rare work that grows more haunting as its futuristic purgatory becomes more real. Published in 1949, the book offers political satirist George Orwell's nightmarish vision of a totalitarian, bureaucratic world and one poor stiff's attempt to find individuality. The brilliance of the novel is Orwell's prescience of modern life—the ubiquity of television, the distortion of the language—and his ability to construct such a thorough version of hell. Required reading for students since it was published, it ranks among the most terrifying novels ever written.", genre: Genre.first)
Book.create(title: "Outliers", author: "Malcom Gladwell", description: "In this stunning book, Malcolm Gladwell takes us on an intellectual journey through the world of 'outliers'--the best and the brightest, the most famous and the most successful. He asks the question: what makes high-achievers different?\nHis answer is that we pay too much attention to what successful people are like, and too little attention to where they are from: that is, their culture, their family, their generation, and the idiosyncratic experiences of their upbringing. Along the way he explains the secrets of software billionaires, what it takes to be a great soccer player, why Asians are good at math, and what made the Beatles the greatest rock band.\nBrilliant and entertaining, Outliers is a landmark work that will simultaneously delight and illuminate.", genre: Genre.second)